async-generator==1.10
blinker==1.4
certifi==2021.10.8
certipy==0.1.3
ipympl==0.8.4
ipython-genutils==0.2.0
munkres==1.1.4
nteract-on-jupyter==2.1.3
pamela==1.0.0
pycurl==7.44.1
PyQt5==5.12.3
PyQt5_sip==4.19.18
PyQtChart==5.12
PyQtWebEngine==5.12.1
webencodings==0.5.1
